version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@3.1.5
  node: circleci/node@5.0.3

workflows:
  version: 2
  continuous:
    jobs:
      - node/test:
          name: test-lambda
          app-dir: code
      - semantic-release/with-existing-config:
          name: semantic-release
          additional_packages: "@google/semantic-release-replace-plugin"
          requires:
            - test-lambda
          context:
            - github-release
          filters:
            branches:
              only:
                - main
