version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@3.1.5
  node: circleci/node@5.0.3

jobs:
  test-lambda:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: code
      - run:
          name: Build app
          command: |
            cd code
            npm run build
      - run:
          name: Run tests
          command: |
            npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit

workflows:
  version: 2
  continuous:
    jobs:
      - test-lambda
      - semantic-release/with-existing-config:
          name: semantic-release
          additional_packages: "@google/semantic-release-replace-plugin"
          requires:
            - test-lambda
          context:
            - github-release
          filters:
            branches:
              only:
                - main
