version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@5.0.0
  node: circleci/node@5.1.0

executors:
  nodejs:
    docker:
      - image: cimg/node:18.16

jobs:
  test-lambda:
    executor: nodejs
    steps:
      - checkout
      - node/install-packages:
          app-dir: code
      - run:
          name: Build app
          command: |
            cd code
            npm run bundle
      - run:
          name: Run tests
          command: |
            cd code
            npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_test_results:
          path: ./code/reports/
  build-lambda:
    executor: nodejs
    steps:
      - checkout
      - node/install-packages:
          app-dir: code
      - run:
          name: Create lambda archive
          command: |
            cd code/
            npm run build
      - persist_to_workspace:
          root: code/
          paths:
            - dist/

workflows:
  version: 2
  continuous:
    jobs:
      - test-lambda
      - build-lambda:
          requires:
            - test-lambda
      - semantic-release/with_existing_config:
          name: semantic-release
          additional_packages: "@google/semantic-release-replace-plugin"
          requires:
            - build-lambda
          context:
            - github-release
          filters:
            branches:
              only:
                - main
